apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/adela683/ci_cd_lab:sha256:8dfc6793c9b425e5d0501bec758a7a4f6c03525bf7749a5941ea593826ea9a96
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
